# Generated by Django 5.2.3 on 2025-08-30 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('banner', models.ImageField(upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='RightSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='right_section/')),
            ],
        ),
        migrations.CreateModel(
            name='StationeryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stationery/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Customer Testimonial', max_length=200)),
                ('subtitle', models.CharField(default='Bulk Stationery. Better Prices. Smarter Supply.', max_length=200)),
                ('profile_image', models.ImageField(upload_to='testimonials/')),
                ('text', models.TextField()),
                ('customer_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trending/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('price_single', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_pack10', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_3plus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('one_line_heading', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('key_features', models.TextField(help_text='Enter features separated by new lines')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mainapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mainapp.product')),
            ],
        ),
    ]
