# Generated by Django 5.2.3 on 2025-08-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='team/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
