# Generated by Django 5.2.3 on 2025-08-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='order',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
