# Generated by Django 5.2.3 on 2025-08-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_aboutgallery_aboutpage_sectionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_top', models.ImageField(upload_to='contact/banner/')),
                ('banner_bottom', models.ImageField(upload_to='contact/banner/')),
            ],
        ),
    ]
